[package]
name = "creator-verifier"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
alloy-primitives = { version = "1.5", features = ["k256", "rlp"] }
anyhow = "1.0"
base64 = "0.22.1"
clap = { version = "4.5", features = ["derive"] }
hex = "0.4"
